### PR TITLE
Fix conditional if field for non-real types

### LINKED ISSUE #214: FieldIf doesn't report value type of source fields 2, 3
A conditional field using a real/bool value for truth condition should delegate to any value type of source fields 2 and 3, which must match e.g. these could be string or mesh location as well as real.
Field.getValueType() is reporting real type for such fields.
This makes the conditional field not work with Fieldassignment.

### PR DESCRIPTION
**Pull request by rchristie**
Fix field assignment for mesh location fields. Guarantee FE_field host mesh is set (except temporarily when reading legacy EX files).

Fixes #214.

### CODE REVIEW

File: src/api/opencmiss/zinc/fieldconditional.h [hunk 1]
```diff
@@ -21,18 +21,25 @@ extern "C" {
...
 
 /**
- * Creates a conditional field with the same number of components as each of the
- * source_fields. For each component, if the value of source_field_one is TRUE
- * (non-zero) then the result will be the value of source_field_two, otherwise the
- * component result will be taken from source_field_three.
+ * Creates a conditional field returning component values from source field two
+ * if the condition source field one is true, otherwise source field three.
+ * The field has the value type and number of components from source fields two
+ * and three, which much match. Source fields two and three of mesh location
```
Comment (alan-wu) [inline src/api/opencmiss/zinc/fieldconditional.h]: Typo - much -> must.

**Review by alan-wu — COMMENTED** [review]
Looks good but found a typo.

**Review by alan-wu — APPROVED** [review]
