### PR TITLE
Attempt at handling images with a pixel depth of less than 8.

### LINKED ISSUE #285: Segmented data image types
I have been using the mapping tools to create segmented data from my masked images and fitting the data to an organ scaffold. However, my masks created with png images do not work but my masks created with jpg images do.  It would be great if png images worked the same as jpg images.

### PR DESCRIPTION
**Pull request by hsorby**
Potentially other ramifications for reading in images with this change.

Fixes #285.

### CODE REVIEW

File: src/general/image_utilities.cpp [hunk 1]
```diff
@@ -5642,7 +5643,7 @@ Extracts parameters from <magick_image> that matter for a Cmgui_image
 				*number_of_components = 3;
 			}
 		}
-		*number_of_bytes_per_component = magick_image->depth/8;
+        *number_of_bytes_per_component = (magick_image->depth == 0) ? 0 : std::max(1, int(magick_image->depth/8));
```
Comment (rchristie) [inline src/general/image_utilities.cpp]: I think this should be:
```
*number_of_bytes_per_component = (magick_image->depth + 7) / 8;
```
So e.g. 12 bits rounds up to 2 bytes.

Can also remove `#include <algorithm>`.

**Review by rchristie — CHANGES_REQUESTED** [review]
FYI My single proposed change passed all tests.

File: src/general/image_utilities.cpp (hunk 1 above)
Comment (hsorby) [reply src/general/image_utilities.cpp]: [2f6db9f](https://github.com/cmlibs/zinc/pull/287/commits/2f6db9f07ad2f1d08c6df821757e2179009b3c64)

**Review by rchristie — APPROVED** [review]
