### PR TITLE
EX file group fixes

### LINKED ISSUE #218: EX version 3 Node/Element groups should not be written if empty
This only occurs when the group is not empty, but the write criterion e.g. 'write only fields with listed names' means no nodes/element are written: the format fails as no content is written. Simplest solution is to list "-1" as the only member in such cases & check that can be read. Cleanest output would be to not write the group at all if can predetermine all objects fail to meet write criterion.

It's a serious bug as the files written are unable to be re-read.

### LINKED ISSUE #219: Non-numeric fields in EX files with coordinate system can't be merged
FE_field now defaults to NOT_APPLICABLE coordinate system until one is set, previously it was RECTANGULAR CARTESIAN for all. Unfortunately, old EX files which set RC for non-numerical fields fail to merge with otherwise identical fields without a coordinate system.

### LINKED ISSUE #220: Destroy node/element does not remove from groups until after change caching ends
Destroying nodes/elements needs to instantly remove the objects from any groups they are in.

### PR DESCRIPTION
**Pull request by rchristie**
Fixes for several issues which broke mapping workflows by being unable to merge old files, or caused writing of invalid EX files.
Fixes #218.
Fixes #219.
Fixes #220.

### CODE REVIEW

File: src/api/opencmiss/zinc/mesh.h [hunk 1]
```diff
@@ -177,35 +177,38 @@ ZINC_API int cmzn_mesh_define_element(cmzn_mesh_id mesh, int identifier,
 
 /**
  * Destroy all elements in mesh, also removing them from any related groups.
+ * All affected element iterators for the mesh or groups are invalidated.
  * All handles to the destroyed element become invalid.
  *
  * @param mesh  Handle to mesh to destroy elements from.
- * @return  Status CMZN_OK if all elements destroyed, any other value if failed.
+ * @return  Result OK if all elements destroyed, or any other error if failed.
```
Comment (hsorby) [inline src/api/opencmiss/zinc/mesh.h]: I think the or part of this line should be `or an error code if failed` (applicable to other similar lines as well).

File: src/computed_field/computed_field_subobject_group.cpp [hunk 2]
```diff
@@ -621,6 +621,36 @@ int Computed_field_element_group::removeElementFaces(cmzn_element_id parent)
 	return return_code;
 }
 
+void Computed_field_element_group::destroyedAllElements()
+{
+	this->labelsGroup->clear();
+	this->invalidateIterators();
+	change_detail.changeRemove();
+	this->field->setChangedPrivate(MANAGER_CHANGE_PARTIAL_RESULT(Computed_field));
```
Comment (hsorby) [inline src/computed_field/computed_field_subobject_group.cpp]: I would be very tempted to put this code inside its own method because it is repeatedly used.

File: src/datastore/labelsgroup.cpp [hunk 3]
```diff
@@ -49,6 +49,22 @@ void DsLabelsGroup::clear()
 	this->indexLimit = 0;
 }
 
+int DsLabelsGroup::removeGroup(DsLabelsGroup& otherGroup)
+{
+	// This could be made faster by working directly with data blocks
+	int numberRemoved = 0;
+	DsLabelIndex index = -1; // DS_LABEL_INDEX_INVALID
```
Comment (hsorby) [inline src/datastore/labelsgroup.cpp]: Is there a reason for using an integer here and not the enumeration?  Maybe it is better to cast it once from a `DS_LABEL_INDEX_INVALID `?

File: src/datastore/labelsgroup.hpp [hunk 4]
```diff
@@ -85,9 +85,16 @@ class DsLabelsGroup : public cmzn::RefCounted
...
+	/** Remove indexes from group which are in otherGroup.
+	 * @param otherGroup  A labels group for the same underlying set.
+	 * @return  Number of indexes removed.
+	 */
+	int removeGroup(DsLabelsGroup& otherGroup);
+
 	/**
-	 * Ensure index is in the group.
+	 * Set whether index is in the group.
 	 * Be careful that index is for this labels.
```
Comment (hsorby) [inline src/datastore/labelsgroup.hpp]: `this labels`?

**Review by hsorby — CHANGES_REQUESTED** [review]
I have some minor comments to be considered. I also have one more pressing concern, the interface for `class FE_nodeset_group` and `class FE_mesh_group` is exactly the same.  I think this should be a single interface that both use.

**Review by hsorby — APPROVED** [review]
Looks like a good addition to me.
