### PR TITLE
Fix reading data and node groups from same ex file

### LINKED ISSUE #147: Can't read both node and data group

### PR DESCRIPTION
**Pull request by rchristie**
Fixes #147

### CODE REVIEW

File: core/source/finite_element/import_finite_element.cpp [hunk 1]
```diff
@@ -1932,7 +2054,7 @@ cmzn_node *EXReader::readNode()
 	}
 	bool result = true;
 	// fill template node if node with identifier already exists (and merge below), otherwise new node
-	FE_node *node = existingNode ? node_template->get_template_node() : returnNode;
+	FE_node *node = existingNode ? nodetemplate->get_template_node() : returnNode;
```
Comment (alan-wu) [inline core/source/finite_element/import_finite_element.cpp]: Should this be this->nodetemplate->get_template_node() for consistence?

**Review by alan-wu — COMMENTED** [review]
Everything else looks good.

File: core/source/finite_element/import_finite_element.cpp (hunk 1 above)
Comment (rchristie) [reply core/source/finite_element/import_finite_element.cpp]: Yes - I always use this->member in new code. Will change and pull.
