### PR TITLE
Zincjs empty export bug fix

### LINKED ISSUE #200: JSON export sometimes gives invalid JSON output.
When creating web-gl output using sparc-converter two of the output files have invalid trailing commas.  Here is one example of the invalid JSON produced:

```
{
	"metadata" : {
		"formatVersion" : 3,
		"description" : "Exported from LibZinc."
	},

	"materials" : [ {
	"DbgColor" : 15658734,
	"DbgIndex" : 0,
	"DbgName" : "my_material",
	"colorDiffuse" : [0.9, 0.9, 0.7],
	"colorSpecular" : [0.1, 0.1, 0.1],
	"shading" : "Phong",
	"specularCoef" : 20,
	"opacity" : 1,
	"vertexColors" : true
	}],

}
```

Looks like it is expecting something further after materials to be present.  Maybe these regions are empty?  Haven't fully investigated yet.

### PR DESCRIPTION
**Pull request by alan-wu**
Mark an ZincJS export as empty and omit it from the metadata file. Update documentation for the relevant APIs. A test has also been added.

fix #200

### CODE REVIEW

File: src/graphics/threejs_export.hpp [hunk 1]
```diff
@@ -24,10 +24,19 @@ class Threejs_export
...
 	int morphVertices, morphColours, morphNormals;
 	int number_of_time_steps;
 	char *groupName, *regionPath;
+	double textureSizes[3];
+	std::string verticesMorphString;
+	std::string colorsMorphString;
+	std::string normalMorphString;
+	std::string facesString;
+	std::string outputString;
+	int isEmpty;
```
Comment (hsorby) [inline src/graphics/threejs_export.hpp]: Why isn't this a `bool`?

Comment (alan-wu) [reply src/graphics/threejs_export.hpp]: Boolean in c++ is not actual boolean but I can change that for clarity.

**Comment by hsorby** [comment]
I have just tried this and it hasn't fixed the problem.

**Comment by alan-wu** [comment]
> 
> 
> I have just tried this and it hasn't fixed the problem.

Do you have the input file and graphics settings I can try it with?

**Comment by hsorby** [comment]
Attached is a simple Argon document with an exnode file.  Using `sparc-converter` (`pip install sparc-converter`) you can run the command (from the unzipped contents directory.):

```
sparc-convert web-gl -p only_surfaces only_surfaces_visualised.neon
```

This command should succeed and generate only valid JSON files linked from the metadata file.

[simple_test_neon_plus_data.zip](https://github.com/OpenCMISS/zinc/files/7429164/simple_test_neon_plus_data.zip)

**Comment by alan-wu** [comment]
> sparc-convert web-gl -p only_surfaces only_surfaces_visualised.neon

Thanks, I received the following error when running the script

obj.append(viewObj)
AttributeError: 'NoneType' object has no attribute 'append'

Not sure if this is from your side or mine - but it is required to test if the memory buffer returned as None now. Memory buffer returned as None can be ignored.

**Comment by hsorby** [comment]
Yes, but I would have thought that we would have zero resources and not one resource that is `None`.

File: src/graphics/threejs_export.hpp [hunk 2]
```diff
@@ -116,6 +116,11 @@ class Threejs_export
 
 	int endExport();
 
+	bool isValid() const
+	{
+		return (isEmpty == false);
```
Comment (hsorby) [inline src/graphics/threejs_export.hpp]: I'm more in favour of the `return !isEmpty;` approach for this type of situation.

File: src/stream/scene_stream.cpp [hunk 3]
```diff
@@ -107,23 +107,34 @@ int cmzn_scene_write(cmzn_scene_id scene,
 				{
 					if (file_resource)
 					{
-						char *file_name = file_resource->getFileName();
-						if (file_name)
+						if (output_string[i].empty() == false)
```
Comment (hsorby) [inline src/stream/scene_stream.cpp]: `if (!output_string[i].empty())`

File: src/stream/scene_stream.cpp [hunk 4]
```diff
@@ -107,23 +107,34 @@ int cmzn_scene_write(cmzn_scene_id scene,
...
 						cmzn_streamresource_file_destroy(&file_resource);
+						i++;
 					}
 					else if (NULL != (memory_resource = cmzn_streamresource_cast_memory(stream)))
 					{
-						char *buffer_out = duplicate_string(output_string[i].c_str());
-						unsigned int buffer_size = static_cast<unsigned int>(strlen(buffer_out));
-						memory_resource->setBuffer(buffer_out, buffer_size);
-						cmzn_streamresource_memory_destroy(&memory_resource);
+						if (output_string[i].empty() == false)
```
Comment (hsorby) [inline src/stream/scene_stream.cpp]: `if (!output_string[i].empty())`

**Comment by hsorby** [comment]
These changes resolve the issue at hand for me, some minor changes and I think this will be good to go.

**Comment by alan-wu** [comment]
Updated styles for false statement check.

**Review by hsorby — APPROVED** [review]

**Review by rchristie — APPROVED** [review]
Only a minor typo in test variable name ('memeory') if you care to fix.
